#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright © 2023 Genome Research Ltd. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# @author Keith James <kdj@sanger.ac.uk>

import argparse
import sys

import structlog

from npg_irods.utilities import check_replicas
from npg_irods.cli import add_logging_arguments, configure_logging
from npg_irods.version import version

description = """
Reads iRODS data object paths from a file or STDIN, one per line and performs
consistency checks on their iRODS replicas.

If any of the paths fail their replica check, the exit code will be non-zero and an 
error message summarising the results will be sent to STDERR.
"""

parser = argparse.ArgumentParser(
    description=description, formatter_class=argparse.RawDescriptionHelpFormatter
)
add_logging_arguments(parser)
parser.add_argument(
    "-i",
    "--input",
    help="Input filename.",
    type=argparse.FileType("r"),
    default=sys.stdin,
)
parser.add_argument(
    "-o",
    "--output",
    help="Output filename.",
    type=argparse.FileType("w"),
    default=sys.stdout,
)
parser.add_argument(
    "-n",
    "--num-replicas",
    help="The number of valid replicas expected. Defaults to 2.",
    type=int,
    default=2,
)
parser.add_argument(
    "--print-pass",
    help="Print to output those paths that pass the check. Defaults to True.",
    action="store_true",
)
parser.add_argument(
    "--print-fail",
    help="Print to output those paths that fail the check. Defaults to False.",
    action="store_true",
)
parser.add_argument(
    "-c",
    "--clients",
    help="Number of baton clients to use. Defaults to 4.",
    type=int,
    default=4,
)
parser.add_argument(
    "-t",
    "--threads",
    help="Number of threads to use. Defaults to 4.",
    type=int,
    default=4,
)
parser.add_argument("--version", help="Print the version and exit", action="store_true")

args = parser.parse_args()
configure_logging(
    config_file=args.log_config,
    debug=args.debug,
    verbose=args.verbose,
    colour=args.colour,
    json=args.json,
)
log = structlog.get_logger("main")


def main():
    if args.version:
        print(version())
        exit(0)

    num_processed, num_passed, num_errors = check_replicas(
        args.input,
        args.output,
        num_replicas=args.num_replicas,
        print_pass=args.print_pass,
        print_fail=args.print_fail,
        num_clients=args.clients,
        num_threads=args.threads,
    )

    if num_errors:
        log.error(
            "Some checks did not pass",
            num_processed=num_processed,
            num_passed=num_passed,
            num_errors=num_errors,
        )
        exit(1)

    log.info(
        "All checks passed",
        num_processed=num_processed,
        num_passed=num_passed,
        num_errors=num_errors,
    )


if __name__ == "__main__":
    main()
